
segmentCount: ${REAPER_SEGMENT_COUNT}
repairParallelism: ${REAPER_REPAIR_PARALELLISM}
repairIntensity: ${REAPER_REPAIR_INTENSITY}
scheduleDaysBetween: ${REAPER_SCHEDULE_DAYS_BETWEEN}
repairRunThreadCount: ${REAPER_REPAIR_RUN_THREADS}
hangingRepairTimeoutMins: ${REAPER_HANING_REPAIR_TIMEOUT_MINS}
storageType: ${REAPER_STORAGE_TYPE}
enableCrossOrigin: ${REAPER_ENABLE_CORS}
incrementalRepair: ${REAPER_INCREMENTAL_REPAIR}
allowUnreachableNodes: ${REAPER_ALLOW_UNREACHABLE_NODES}
enableDynamicSeedList: ${REAPER_ENABLE_DYNAMIC_SEEDS}

autoScheduling:
  enabled: ${REAPER_AUTO_SCHEDULE_ENABLED}
  initialDelayPeriod: ${REAPER_AUTO_SCHEDULE_INITIAL_DELAY_PERIOD}
  periodBetweenPolls: ${REAPER_AUTO_SCHEDULE_PERIOD_BETWEEN_POLLS}
  timeBeforeFirstSchedule: ${REAPER_AUTO_SCHEDULE_TIME_BETWEEN_FIRST_SCHEDULE}
  scheduleSpreadPeriod: ${REAPER_AUTO_SCHEDULE_TIME_BETWEEN_FIRST_SCHEDULE}
  excludedKeyspaces: ${REAPER_AUTO_SCHEDULE_EXCLUDED_KEYSPACES}

jmxPorts: ${REAPER_JMX_PORTS}

logging:
  level: ${REAPER_LOGGING_ROOT_LEVEL}
  loggers: ${REAPER_LOGGERS}
  appenders:
    - type: console
      logFormat: ${REAPER_LOGGING_FORMAT}

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${REAPER_APP_PORT}
      bindHost: ${REAPER_APP_BIND_HOST}
  adminConnectors:
    - type: http
      port: ${REAPER_ADMIN_PORT}
      bindHost: ${REAPER_ADMIN_BIND_HOST}
  requestLog:
    appenders: []

